import {
  User,
  StudentProfile,
  ParentData,
  SchoolOrigin,
  AddressData,
  Application,
  DocumentItem,
  School,
  SystemSettings,
  Announcement,
  AuditLog,
} from '../types/sipma';

export const INITIAL_SCHOOLS: School[] = [
  {
    school_id: 'SCH-MAN1',
    school_name: 'MAN 1 Kota Cerdas',
    school_code: 'MAN01',
    nsm: '131132710001',
    npsn: '20277101',
    level: 'MA',
    address: 'Jl. Pemuda No. 45, Kebayoran Baru, Jakarta Selatan',
    latitude: -6.238271,
    longitude: 106.802315,
    zoning_radius_km: 5.0,
    quota_zonasi: 100,
    quota_afirmasi: 40,
    quota_prestasi: 40,
    quota_mutasi: 20,
    status: 'active',
    principal_name: 'Dr. H. Ahmad Dahlan, M.Pd.',
    headmaster_nip: '197205121998031002',
    contact_phone: '021-7201928',
    contact_email: 'info@man1kotacerdas.sch.id',
    reregistration_start_date: '2026-07-01',
    reregistration_end_date: '2026-07-07',
    reregistration_time: '08.00 - 14.00 WIB (Senin - Sabtu)',
    reregistration_location: 'Ruang Pelayanan Terpadu Satu Pintu (PTSP) Gedung A Lantai 1',
    reregistration_notes: 'Wajib didampingi orang tua/wali, berpakaian seragam rapi, serta membawa seluruh berkas asli dan fotokopi legalisir 2 rangkap.',
  },
  {
    school_id: 'SCH-MAN2',
    school_name: 'MAN 2 Moderasi Beragama',
    school_code: 'MAN02',
    nsm: '131132710002',
    npsn: '20277104',
    level: 'MA',
    address: 'Jl. Radio Dalam No. 88, Kebayoran Baru, Jakarta Selatan',
    latitude: -6.248912,
    longitude: 106.791245,
    zoning_radius_km: 5.5,
    quota_zonasi: 120,
    quota_afirmasi: 45,
    quota_prestasi: 45,
    quota_mutasi: 20,
    status: 'active',
    principal_name: 'Dr. H. M. Zainal Arifin, M.Pd.I',
    headmaster_nip: '197408151999031004',
    contact_phone: '021-7254890',
    contact_email: 'info@man2moderasi.sch.id',
    reregistration_start_date: '2026-07-01',
    reregistration_end_date: '2026-07-08',
    reregistration_time: '08.00 - 14.00 WIB',
    reregistration_location: 'Sekretariat Panitia PPDB MAN 2 Moderasi Beragama',
    reregistration_notes: 'Membawa berkas asli: Ijazah/SKL, Kartu Keluarga, Akta Kelahiran, dan pas foto terbaru 3x4 (3 lembar).',
  },
  {
    school_id: 'SCH-MAN3',
    school_name: 'MAN 3 Riset & Teknologi',
    school_code: 'MAN03',
    nsm: '131132710003',
    npsn: '20277105',
    level: 'MA',
    address: 'Jl. Gatot Subroto No. 19, Mampang Prapatan, Jakarta Selatan',
    latitude: -6.241500,
    longitude: 106.825800,
    zoning_radius_km: 6.0,
    quota_zonasi: 110,
    quota_afirmasi: 35,
    quota_prestasi: 50,
    quota_mutasi: 15,
    status: 'active',
    principal_name: 'Hj. Nurul Hidayati, M.Si',
    contact_phone: '021-7918302',
    contact_email: 'info@man3riset.sch.id',
  },
  {
    school_id: 'SCH-MTSN2',
    school_name: 'MTsN 2 Insan Cendekia',
    school_code: 'MTS02',
    nsm: '121132710002',
    npsn: '20277102',
    level: 'MTs',
    address: 'Jl. Madani No. 12, Tebet, Jakarta Selatan',
    latitude: -6.230142,
    longitude: 106.852914,
    zoning_radius_km: 4.0,
    quota_zonasi: 140,
    quota_afirmasi: 60,
    quota_prestasi: 60,
    quota_mutasi: 20,
    status: 'active',
    principal_name: 'Dra. Hj. Siti Maryam, M.Ag.',
    contact_phone: '021-8302910',
    contact_email: 'info@mtsn2cendekia.sch.id',
  },
  {
    school_id: 'SCH-MTSN1',
    school_name: 'MTsN 1 Prestasi Luhur',
    school_code: 'MTS01',
    nsm: '121132710001',
    npsn: '20277106',
    level: 'MTs',
    address: 'Jl. Dr. Saharjo No. 100, Tebet Barat, Jakarta Selatan',
    latitude: -6.225100,
    longitude: 106.848200,
    zoning_radius_km: 4.5,
    quota_zonasi: 130,
    quota_afirmasi: 50,
    quota_prestasi: 50,
    quota_mutasi: 20,
    status: 'active',
    principal_name: 'H. Abdul Rasyid, S.Ag, M.Pd',
    contact_phone: '021-8291045',
    contact_email: 'info@mtsn1prestasi.sch.id',
  },
  {
    school_id: 'SCH-MIN3',
    school_name: 'MIN 3 Teladan Sejahtera',
    school_code: 'MI03',
    nsm: '111132710003',
    npsn: '20277103',
    level: 'MI',
    address: 'Jl. Pendidikan Islami No. 8, Pasar Minggu, Jakarta Selatan',
    latitude: -6.284210,
    longitude: 106.839800,
    zoning_radius_km: 3.0,
    quota_zonasi: 80,
    quota_afirmasi: 30,
    quota_prestasi: 30,
    quota_mutasi: 10,
    status: 'active',
    principal_name: 'Drs. H. Syarif Hidayatullah',
    contact_phone: '021-7801234',
    contact_email: 'info@min3teladan.sch.id',
  },
  {
    school_id: 'SCH-MIN1',
    school_name: 'MIN 1 Ceria Al-Qurani',
    school_code: 'MI01',
    nsm: '111132710001',
    npsn: '20277107',
    level: 'MI',
    address: 'Jl. Warung Buncit Raya No. 40, Pancoran, Jakarta Selatan',
    latitude: -6.262500,
    longitude: 106.831200,
    zoning_radius_km: 3.5,
    quota_zonasi: 90,
    quota_afirmasi: 35,
    quota_prestasi: 35,
    quota_mutasi: 10,
    status: 'active',
    principal_name: 'Hj. Zubaidah, M.Pd.I',
    contact_phone: '021-7981245',
    contact_email: 'info@min1ceria.sch.id',
  },
];

export const INITIAL_USERS: User[] = [
  {
    user_id: 'USR-ADMIN-PUSAT',
    name: 'Administrator Pusat PPDB',
    email: 'admin.pusat@kemenag.go.id',
    phone: '081198765432',
    role: 'admin_pusat',
    status: 'active',
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
  {
    user_id: 'USR-ADMIN-MAN1',
    name: 'Panitia PPDB MAN 1',
    email: 'admin.man1@madrasah.id',
    phone: '081234567890',
    role: 'admin_sekolah',
    school_id: 'SCH-MAN1',
    status: 'active',
    created_at: '2026-01-05T08:00:00Z',
    updated_at: '2026-01-05T08:00:00Z',
  },
];

export const INITIAL_STUDENTS: Record<string, StudentProfile> = {};

export const INITIAL_PARENTS: Record<string, ParentData> = {};

export const INITIAL_SCHOOL_ORIGINS: Record<string, SchoolOrigin> = {};

export const INITIAL_ADDRESSES: Record<string, AddressData> = {};

export const INITIAL_APPLICATIONS: Application[] = [];

export const INITIAL_DOCUMENTS: DocumentItem[] = [];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    announcement_id: 'ANC-001',
    title: 'Pembukaan Penerimaan Murid Baru (PPDB) Madrasah TP 2026/2027',
    content: 'Pendaftaran murid baru dibuka untuk 4 jalur: Jalur Zonasi, Afirmasi, Prestasi (Akademik/Non-Akademik/Tahfidz), dan Mutasi (Perpindahan Tugas Orang Tua/Wali). Calon peserta didik dimohon mempersiapkan dokumen persyaratan asli.',
    date: '2026-02-01',
    is_published: true,
    target_role: 'all',
    author_name: 'Panitia Pusat Kemenag',
  },
  {
    announcement_id: 'ANC-002',
    title: 'Petunjuk Teknis Penentuan Titik Koordinat Rumah Jalur Zonasi',
    content: 'Bagi pendaftar Jalur Zonasi, pastikan titik penanda (marker) pada peta interaktif berada tepat di atas atap rumah tempat tinggal sesuai alamat pada Kartu Keluarga (KK). Radius zonasi maksimal adalah 5,00 km.',
    date: '2026-02-03',
    is_published: true,
    target_role: 'calon_murid',
    school_id: 'SCH-MAN1',
    author_name: 'Panitia PPDB MAN 1',
  },
  {
    announcement_id: 'ANC-003',
    title: 'Jadwal Verifikasi Portofolio Jalur Prestasi dan Berkas Mutasi',
    content: 'Calon peserta didik Jalur Prestasi (KSM, OSN, Tahfidz) dan Jalur Mutasi (SK Penugasan Orang Tua) wajib memastikan dokumen pendukung terunggah jelas untuk verifikasi keaslian oleh panitia seleksi madrasah.',
    date: '2026-02-10',
    is_published: true,
    target_role: 'calon_murid',
    school_id: 'SCH-MAN1',
    author_name: 'Panitia PPDB MAN 1',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  spreadsheet_id: '1aBcDeFgHiJkLmNoPqRsTuVwXyZ_SIPMA2026_SampleID',
  drive_root_folder_id: '1FolderId_SIPMA_Root_SampleStorage',
  gas_web_app_url: '',
  maps_api_key: '',
  application_year: '2027',
  academic_year_label: '2027/2028',
  app_name: 'SIPMA',
  app_tagline: 'Sistem Penerimaan Murid Madrasah',
  app_logo: '',
  default_school_id: 'SCH-MAN1',
  max_file_size_mb: 5,
  registration_open: true,
  announcement_open: true,
  demo_mode: true,
  db_config_locked: true,
  db_config_pin: '123456',
  realtime_sync_enabled: true,
  auto_sync_interval_sec: 15,
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    log_id: 'LOG-001',
    timestamp: '2026-02-01T08:00:00Z',
    user_id: 'USR-ADMIN-PUSAT',
    username: 'admin.pusat@kemenag.go.id',
    role: 'admin_pusat',
    action: 'SYSTEM_INIT',
    target: 'Database & Settings',
    description: 'Inisialisasi sistem penerimaan murid madrasah tahun ajaran 2026/2027.',
    status: 'success',
  },
];
